"""
Generate src/data/builtin_shapes.rs from every shapes_*.yaml file in a directory.

This reads the same YAML files produced by build_yaml_for_folder.py and emits
plain Rust code that constructs a Vec<ReferenceShape> directly — no YAML
parsing at runtime for the built-in shape library.

Usage:
    py generate_builtin_shapes_rs.py src/data/shapes src/data/builtin_shapes.rs
"""

import re
import sys
from pathlib import Path

# Matches an entry header, e.g. "TP-3:"
ENTRY_RE = re.compile(r"^(\S+):\s*$")
FIELD_RE = re.compile(r"^\s*(id|symmetry|name):\s*(.+?)\s*$")
COORD_RE = re.compile(r"-\s*\[\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\]")


def parse_yaml_file(path: Path):
    """Parse one shapes_Nvertex.yaml file into a list of dicts."""
    entries = []
    current = None
    section = None  # "vertices" or "center" or None

    for raw_line in path.read_text().splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue

        # New entry (no leading whitespace, ends with ':')
        if not line.startswith(" ") and (m := ENTRY_RE.match(line)):
            if current is not None:
                entries.append(current)
            current = {"symbol": m.group(1), "vertices": [], "center": []}
            section = None
            continue

        if current is None:
            continue

        if (m := FIELD_RE.match(line)):
            key, value = m.groups()
            if key == "id":
                current["id"] = int(value)
            else:
                current[key] = value
            continue

        stripped = line.strip()
        if stripped == "vertices:":
            section = "vertices"
            continue
        if stripped == "center:":
            section = "center"
            continue

        if (m := COORD_RE.search(line)) and section in ("vertices", "center"):
            x, y, z = (float(v) for v in m.groups())
            current[section].append((x, y, z))
            continue

    if current is not None:
        entries.append(current)

    return entries


def rust_coord(coord) -> str:
    x, y, z = coord
    return f"[{x!r}, {y!r}, {z!r}]"


def rust_shape_literal(entry) -> str:
    vertices = ", ".join(rust_coord(v) for v in entry["vertices"])
    center = rust_coord(entry["center"][0]) if entry["center"] else "[0.0, 0.0, 0.0]"
    return (
        "ReferenceShape {\n"
        f'            symbol: "{entry["symbol"]}".to_string(),\n'
        f'            name: "{entry["name"]}".to_string(),\n'
        f'            id: {entry["id"]},\n'
        f'            symm: "{entry["symmetry"]}".to_string(),\n'
        f"            centre: {center},\n"
        f"            vertices: vec![{vertices}],\n"
        "        }"
    )


def generate(shapes_dir: Path, out_path: Path):
    yaml_files = sorted(shapes_dir.glob("shapes_*vertex.yaml"))
    if not yaml_files:
        print(f"no shapes_*vertex.yaml files found in {shapes_dir}", file=sys.stderr)
        sys.exit(1)

    all_entries = []
    for yf in yaml_files:
        entries = parse_yaml_file(yf)
        all_entries.extend(entries)
        print(f"parsed {yf.name}: {len(entries)} shapes")

    # group entries by vertex count (number of vertices == number of ligands, N)
    by_n = {}
    for entry in all_entries:
        n = len(entry["vertices"])
        by_n.setdefault(n, []).append(entry)

    lines = []
    lines.append("// AUTO-GENERATED by generate_builtin_shapes_rs.py - do not edit by hand.")
    lines.append("// Regenerate from src/data/shapes/*.yaml if the shape library changes.")
    lines.append("")
    lines.append("use std::collections::HashMap;")
    lines.append("use crate::yaml::ReferenceShape;")
    lines.append("")
    lines.append("pub fn builtin_shapes() -> HashMap<u8, Vec<ReferenceShape>> {")
    lines.append("    let mut map: HashMap<u8, Vec<ReferenceShape>> = HashMap::new();")
    lines.append("")
    for n in sorted(by_n.keys()):
        lines.append(f"    map.insert({n}, vec![")
        for entry in by_n[n]:
            lines.append(f"        {rust_shape_literal(entry)},")
        lines.append("    ]);")
        lines.append("")
    lines.append("    map")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path} ({len(all_entries)} total shapes)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: generate_builtin_shapes_rs.py <shapes_dir> <output.rs>", file=sys.stderr)
        sys.exit(1)
    generate(Path(sys.argv[1]), Path(sys.argv[2]))
