"""
Generate tests/polynator_reference.csv: Polynator's own values for the structures that PLAN.md
item 19 (`dshm`) uses as parity fixtures.

Runs Polynator (Link & Niewa, J. Appl. Cryst. 2023, 56, 1855) headless, from a local copy of its
Python source. Polynator is not part of cosmochlore and nothing from it is copied here (its
source carries no licence statement); download it from
https://www.iac.uni-stuttgart.de/forschung/akniewa/downloads/ and point --polynator (or the
POLYNATOR_DIR environment variable) at the folder holding polynator_main.py. It needs numpy.

Settings mirror cosmochlore's cshm defaults: the first atom of the .xyz is the centre and is
fitted, the other atoms are its ligands (Polynator's "fixed number" rule with n = atoms - 1), and
every model with that vertex count is fitted (no redundant-model skipping). For each model the CSV
holds Polynator's delta, S = delta^2 / 100 (the cshm scale) and its fitted parameters.

Usage:
    py generate_polynator_fixtures.py --polynator C:/path/to/polynator_1.7.1_python
        [--out tests/polynator_reference.csv] [structure.xyz ...]
"""

import argparse
import csv
import hashlib
import io
import os
import re
import sys
from contextlib import redirect_stdout
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def run_polynator(pm, path):
    """Fit every Polynator model with the right vertex count to one cosmochlore .xyz file."""
    lines = path.read_text().splitlines()
    labels = [l.split()[0] for l in lines[2:2 + int(lines[0])]]
    element = lambda label: re.match(r"[A-Z][a-z]?", label).group(0)
    parsed = pm.InputFileParser(path.name, str(path))
    dp = deepcopy(pm.DICT_INPUT_DEFAULT)
    dp["dict_assignment_variants"] = pm.get_dict_assignment_variants(
        pm.DICT_ASSIGNMENTS, pm.DICT_MODEL_BITS_N_BOBS, pm.DICT_MODEL_BLUEPRINTS)
    dp.update(
        input_dir=str(path.parent), input_filenames=[path.name],
        dict_input_file_data={path.name: (parsed.symmetry_matrices, parsed.cell_parameters,
                                          parsed.atom_data, parsed.bond_data)},
        create_molecules=False, fit_central_atoms=True, fit_ligands=True,
        connectivity="fixed_number", n_ligands=len(labels) - 1, skip_redundant_models=False,
        dict_graph_tracing_keys={"select": [], "reduce": [], "block": []},
        central_atom_criteria={"or": [labels[0]]},
        ligand_atom_criteria={"or": sorted({element(l) for l in labels[1:]})},
    )
    process = pm.MainProcess(dp)
    with redirect_stdout(io.StringIO()):
        process.prepare()
        process.run()
    arrangement = process.structures[0].arrangement_objects[0]
    for model in sorted(arrangement.model_objects, key=lambda m: (m.delta, m.name)):
        params = ";".join(f"{k}={float(v):.6f}" for k, v in model.dict_parameter_values.items())
        yield {
            "structure": path.name, "model": model.name,
            "point_group": model.dict_info.get("point_group", ""),
            "n_variables": model.n_variables, "delta": f"{model.delta:.6f}",
            "s": f"{0.01 * model.delta ** 2:.6f}", "parameters": params,
        }


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("structures", nargs="*", default=[str(ROOT / "tests" / "FeHS.xyz")])
    ap.add_argument("--polynator", default=os.environ.get("POLYNATOR_DIR"),
                    help="folder with polynator_main.py (or set POLYNATOR_DIR)")
    ap.add_argument("--out", default=str(ROOT / "tests" / "polynator_reference.csv"))
    args = ap.parse_args()
    if not args.polynator or not (Path(args.polynator) / "polynator_main.py").is_file():
        sys.exit("error: pass --polynator DIR (or set POLYNATOR_DIR) to a folder with "
                 "polynator_main.py; see this script's docstring")

    source = Path(args.polynator) / "polynator_main.py"
    sys.path.insert(0, str(source.parent))
    import polynator_main as pm  # noqa: E402  (located at run time)

    version = next((l.strip("# \n") for l in source.read_text(encoding="utf-8").splitlines()
                    if re.match(r"#\s*Polynator v", l)), "unknown version")
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    rows = [row for s in args.structures for row in run_polynator(pm, Path(s).resolve())]

    with open(args.out, "w", newline="") as fh:
        fh.write("# Generated by generate_polynator_fixtures.py; see PLAN.md item 19. Do not edit.\n")
        fh.write(f"# {version} ({source.parent.name}), polynator_main.py sha256 {digest}\n")
        fh.write("# Centre fitted, all other atoms ligands, no redundant-model skipping.\n")
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {len(rows)} rows to {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
